import { PageParams } from "./pageParams";

export const authors: string[] = [
  'Abdul Kalam',
  'Abdus Salam',
  'Abraham Lincoln',
  'Abu Bakr',
  'Abu Bakr (R.A)',
  'Albert Camus',
  'Albert Einstein',
  'Ali ibn Abi Talib (R.A)',
  'Anne Frank',
  'Aristotle',
  'Ayn Rand',
  'Benjamin Franklin',
  'Bill Cosby',
  'Bill Gates',
  'Carl Sagan',
  'Coco Chanel',
  'Confucius',
  'Elizabeth Kenny',
  'Ernest Hemingway',
  'Friedrich Nietzsche',
  'Hamad Bin Isa Al Khalifa',
  'Henry Ford',
  'J. K. Rowling',
  'John F. Kennedy',
  'John Stott',
  'Leonardo Da Vinci',
  'Marie Curie',
  'Marilyn Monroe',
  'Mark Twain',
  'Martin Luther King  Jr.',
  'Mother Teresa',
  'Muhammad Ali',
  'Muhammad Iqbal',
  'Nelson Mandela',
  'Oprah Winfrey',
  'Paulo Coelho',
  'Robin Williams',
  'Rumi',
  'Socrates',
  'Stephen King',
  'Steve Jobs',
  'Theodore Roosevelt',
  'Umar ibn Al-Khattāb (R.A)',
  'Victor Hugo',
  'Walt Disney',
  'Warren Buffett',
  'William Shakespeare',
  'Willie Nelson',
  'Winston Churchill',
  'Zig Ziglar'
];

export const DEFAULT_PAGE_PARAMS = {
  pageSize: 20,
  skip: 0,
}